name: Performance tests
on:
  schedule:
    - cron: '0 10 * * SUN,SAT'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
          java-version: 17
    - name: Run performance tests
      run: mvn -B -U compile verify -f performance-test/pom.xml
      
